name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

env:
  NODE_VERSION: '20.x'  # Angular 19 requiere Node 18+

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4  # Actualizado a v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g @angular/cli@latest

      - name: Build Angular app
        run: |
          rm -rf dist
          ng build --configuration production --output-path=dist/azure-deploy
          
          # Mover archivos a la estructura que Azure espera
          mkdir -p dist/deploy-ready
          cp -r dist/azure-deploy/browser/* dist/deploy-ready/
          cp src/staticwebapp.config.json dist/deploy-ready/

      - name: Verify build structure
        run: |
          echo "=== Estructura generada ==="
          ls -R dist/azure-deploy
          echo "=== Estructura lista para deploy ==="
          ls -R dist/deploy-ready
          [ -f "dist/deploy-ready/index.html" ] || (echo "❌ Error: index.html no encontrado" && exit 1)

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_RIVER_01744AF0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist/deploy-ready"  # Cambiado a la nueva ruta
          api_location: ""
          output_location: ""  # Ahora vacío porque app_location apunta al destino final
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_RIVER_01744AF0F }}
          action: "close"
